use newt_core::{
    agentic::{openai_chat_complete, ChatCtx},
    BackendKind, Caveats, MemMessage, NoMcp, PermissionGate,
};
use std::sync::atomic::AtomicBool;

pub async fn run(
    url: &str,
    workspace: &str,
    caveats: &Caveats,
    gate: &mut dyn PermissionGate,
    cancel: &AtomicBool,
) {
    let messages = vec![
        MemMessage::system("Execute the scripted tool calls."),
        MemMessage::user("Run the script"),
    ];
    openai_chat_complete(
        ChatCtx {
            shell_dialect: newt_core::agentic::shell_dialect_sentence(false, false),
            command_budget: Default::default(),
            overflow_retry: Default::default(),
            run_allowance: None,
            verify_outcomes: false,
            round_cap_hit: None,
            smart_harness: None,
            rewrites_history: true,
            url,
            model: "grant-retry-test",
            kind: BackendKind::Openai,
            emits_leading_reasoning: false,
            api_key: Some("sk-test"),
            messages: &messages,
            task: "do the thing",
            workspace,
            default_command_cwd: None,
            worktree_session: None,
            color: false,
            markdown: false,
            tool_offload: false,
            spill_store: None,
            disclosure: None,
            compaction_store: None,
            scratchpad: false,
            scratchpad_store: None,
            code_search: None,
            where_is: None,
            nav: None,
            exposure: Default::default(),
            experience_store: None,
            step_ledger: None,
            caveats,
            persona_tools: None,
            cognition: None,
            chat_completions_capability: Default::default(),
            responses_capability: Default::default(),
            openai_api: Default::default(),
            output_allowance: None,
            attempt_ledger: None,
            reasoning_replay_scope: newt_core::model_card::ReasoningReplayScope::Never,
            max_tool_rounds: 5,
            narration_nudge_cap: 1,
            action_nudges: true,
            prompt_disposition: newt_core::agentic::PromptDisposition::Act,
            prompt_intake: None,
            workflow_grace_rounds: 0,
            tool_output_lines: 20,
            debug: false,
            trace: false,
            num_ctx: None,
            input_ceiling_pct: 80,
            low_budget_pct: 15,
            connect_timeout_secs: 5,
            inference_timeout_secs: 120,
            mid_loop_trim_threshold: 40,
            compaction_trigger_policy: newt_core::CompactionTriggerPolicy::HeadroomAware,
            mid_loop_trim_tokens: None,
            max_ok_input: None,
            build_check_cmd: None,
            safe_context: None,
            recover_cw_400: None,
            note_sink: None,
            note_nudge: None,
            recall_source: None,
            memory_source: None,
            summarizer: None,
            compress_state: None,
            tool_events: None,
            phantom_reaches: None,
            end_reason: None,
            solve_obs: None,
            permission_gate: Some(gate),
            on_round_usage: None,
            estimate_ratio: None,
            estimation: newt_core::TokenEstimation::default(),
            summary_input_cap_floor_chars: 8_192,
            exec_floor: None,
            write_ledger: None,
            attribution: None,
            cancel: Some(cancel),
            live_tool_output: None,
            git_tool: None,
            crew_runner: None,
            operating_mode_control: None,
            plan_mode_control: None,
            plan_draft_sink: None,
            steering: None,
            completed_spill_renderer: None,
        },
        &mut NoMcp,
    )
    .await
    .expect("scripted provider turn");
}
