//! `.scratch/` — the project-local **ephemeral** state root (#844).
//!
//! Crew worktrees, the crew's shared cargo target, and per-session plans live
//! under `<repo>/.scratch/`, NOT under `.newt/`. That keeps `.newt/` for
//! *tracked* project config (`config.toml`, `agent-identity.toml`, `plan.md`,
//! `language-packs/`) and puts everything generated/ephemeral in one clearly
//! throwaway place — no more mixed tracked/untracked noise in `git status`
//! (the failure mode that let a 201 MB `crew-target` and a leftover worktree get
//! swept into a commit by `git add -A`).
//!
//! **The ignore is baked into the harness, not the model.** [`ensure_scratch`]
//! writes `.scratch/.gitignore` containing `*` (exactly the pattern cargo uses
//! for `target/.gitignore`), so git ignores every scratch file *independent of*
//! the repo's root `.gitignore`. Every code path that creates scratch calls it,
//! so the ignore can never be forgotten — a crew or session can't accidentally
//! make its scratch committable.

use std::io;
use std::path::{Path, PathBuf};

/// The ephemeral scratch root under `base`: `<base>/.scratch`. Pure.
#[must_use]
pub fn scratch_root(base: &Path) -> PathBuf {
    base.join(".scratch")
}

/// Contents of the self-ignoring `.scratch/.gitignore`. `*` ignores every file
/// under `.scratch/` regardless of the repo's root `.gitignore`, so the harness
/// owns the ignore and the model cannot forget it.
pub const SCRATCH_GITIGNORE: &str =
    "# Auto-generated by newt: ephemeral scratch (#844). Never commit this dir.\n*\n";

/// Create `<base>/.scratch/` and ensure its self-ignoring `.gitignore` exists.
/// Idempotent — call it from every scratch-write path (crew worktrees, the crew
/// target, per-session plans) so scratch is *never* committable, even if the
/// root `.gitignore` is missing the entry. Returns the scratch root.
///
/// # Errors
/// Propagates a directory-create or `.gitignore` write failure.
pub fn ensure_scratch(base: &Path) -> io::Result<PathBuf> {
    let root = scratch_root(base);
    std::fs::create_dir_all(&root)?;
    let ignore = root.join(".gitignore");
    if !ignore.exists() {
        std::fs::write(&ignore, SCRATCH_GITIGNORE)?;
    }
    Ok(root)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scratch_root_is_dot_scratch_under_base() {
        assert_eq!(
            scratch_root(Path::new("/repo")),
            PathBuf::from("/repo/.scratch")
        );
    }

    #[test]
    fn gitignore_body_ignores_everything() {
        // `*` on its own line is the whole point — git ignores all scratch.
        assert!(SCRATCH_GITIGNORE.lines().any(|l| l.trim() == "*"));
    }

    #[test]
    fn ensure_scratch_creates_dir_and_self_ignore() {
        let tmp = tempfile::tempdir().unwrap();
        let root = ensure_scratch(tmp.path()).unwrap();
        assert!(root.is_dir(), "scratch root created");
        let ignore = root.join(".gitignore");
        assert!(ignore.is_file(), ".scratch/.gitignore written");
        assert_eq!(std::fs::read_to_string(&ignore).unwrap(), SCRATCH_GITIGNORE);
    }

    #[test]
    fn ensure_scratch_is_idempotent_and_preserves_existing_ignore() {
        let tmp = tempfile::tempdir().unwrap();
        ensure_scratch(tmp.path()).unwrap();
        // A user (or a prior run) customized the ignore — do not clobber it.
        let ignore = scratch_root(tmp.path()).join(".gitignore");
        std::fs::write(&ignore, "*\n!keep.txt\n").unwrap();
        ensure_scratch(tmp.path()).unwrap();
        assert_eq!(std::fs::read_to_string(&ignore).unwrap(), "*\n!keep.txt\n");
    }
}
